package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/threehook/esco-search/transport/gql/gen"
)

// SearchBeroepenViaPrompt is the resolver for the searchBeroepenViaPrompt field.
func (r *queryResolver) SearchBeroepenViaPrompt(ctx context.Context, prompt gen.SearchBeroepenViaPromptInput) (*gen.SearchBeroepenViaPromptPayload, error) {
	matches, err := r.App.SearchBeroepenViaPrompt(ctx, prompt.SearchRequest)

	genBeroepenMatches := make([]*gen.BeroepenMatch, len(matches))
	for i, match := range matches {
		genBeroepenMatches[i] = &gen.BeroepenMatch{
			Code:   match.Code,
			Beroep: match.Beroep,
		}

	}

	return &gen.SearchBeroepenViaPromptPayload{
		Matches: genBeroepenMatches,
	}, err
}

// Query returns gen.QueryResolver implementation.
func (r *Resolver) Query() gen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
